version: "3.8"

volumes:
  pgrs_api_vol:

services:
  api_service:
    build: ./
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB_ADDR=postgres
      - POSTGRES_DB_PORT=5432
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=todos
    volumes:
      - pgrs_api_vol:/data/db
    restart: always