version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - '5432:5432'

  api:
    image:
    environment:
    depends_on:
      - db
    ports:
      - '8080:8080'